### ISSUE TITLE
Auto-Complete for Controlled Types on Ingest Form

### ISSUE THREAD

**Issue by tpendragon** [OregonDigital/ControlledVocabularyManager#10]

**Comment by srabun** [comment]
for fields like "type" where we only use like 4 options...dropdown

**Comment by wickr** [comment]
These are the types:

"Concept": "http://www.w3.org/2004/02/skos/core#Concept",
"CorporateName": "http://www.w3.org/2004/02/skos/core#CorporateName",
"Geographic": "http://www.w3.org/2004/02/skos/core#Geographic",
"PersonalName": "http://www.w3.org/2004/02/skos/core#PersonalName",
"Title": "http://www.w3.org/2004/02/skos/core#Title",
"Topic": "http://www.w3.org/2004/02/skos/core#Topic",

**Comment by revgum** [comment]
"a quick dropdown that maps to specific properties" ~ Brandon

**Comment by revgum** [comment]
Possibly:
14:07 < tjohnson> gumj_: you can definitely do `my_resource.type << some_uri`
14:07 < tjohnson> but, again, this may change how your accessors for other resources behave

Take in a user-selected type, then during save set a property to refer to the selected type. https://gist.github.com/no-reply/66f0bf6fd5bcb24de84b

**Comment by revgum** [comment]
Each of these types is a new model, inheriting from Term. The form will pass in a selected type, and the controller persists that new instance of that model.
