### ISSUE TITLE
Create a field to add language specification for literals

### ISSUE THREAD

**Issue by mickeroo** [OregonDigital/ControlledVocabularyManager#103]
On the ingest form, we need to add the language specification for any literals.

**Comment by mickeroo** [comment]
Julia needs the ability to specify the language tag for any literals.

**Comment by srabun** [comment]
default to English, then allow people to choose more options

**Comment by srabun** [comment]
check what RDF spec wants in terms of "en" vs "eng"

**Comment by no-reply** [comment]
Use the shortest available ISO 639 code ('en' in this case). See [0], and
references linked from there.

[0]
http://www.w3.org/TR/2014/REC-rdf11-concepts-20140225/#section-Graph-Literal
