### ISSUE TITLE
Add text on home page describing OpaqueNamespace.org

### ISSUE THREAD

**Issue by tpendragon** [OregonDigital/ControlledVocabularyManager#120]

**Comment by wickr** [comment]
Possible content:
Guidelines for creating URIs
Link to Cool URIs - https://www.w3.org/TR/cooluris/
Linked Data principles - link?
Note about modeling vocabs/terms that have schemas but no RDF representation, and how we'll work with them and link to them if they eventually come online (VRA, GeoRSS, etc.)
