### ISSUE TITLE
Add a date option and additional items (see comment) to the term creation form

### ISSUE THREAD

**Issue by mickeroo** [OregonDigital/ControlledVocabularyManager#126]
From @jsimic re: the CVM scoping meeting:

One of the things I meant to bring up is adding a date option to the term creation form. It’s often the only way I can differentiate between two people with the same name.

**Comment by srabun** [comment]
add date, type, alternate name, and additional name to the form (schema.org) Date and Type are really important

**Comment by revgum** [comment]
more properties and testing involved

**Comment by revgum** [comment]
size was more like a 2, simple update but one property belongs with and depends on other issues related to term types
