### ISSUE TITLE
Add Language label on the Show pages

### ISSUE THREAD

**Issue by wickr** [OregonDigital/ControlledVocabularyManager#141]

**Comment by revgum** [comment]
"language label and the language code" ~ Brandon/Ryan

**Comment by wickr** [comment]
Show 'English (en)'  'Spanish (es)'

**Comment by revgum** [comment]
Brandon and I discovered a pull request to enable pulling out the language literal from a term.. 

@term.get_values(RDF::DC.title, :literal => true)     #returns  [:en]

https://github.com/ActiveTriples/ActiveTriples/pull/70/files

**Comment by straleyb** [comment]
This work was actually a 1, however, was dependent on a much larger feature which was multiple language support (13)
