### ISSUE TITLE
Make language drop-down on Edit select what value is already set

### ISSUE THREAD

**Issue by wickr** [OregonDigital/ControlledVocabularyManager#142]

**Comment by mickeroo** [comment]
If the value hasn't been set yet, default to English, since that's probably what people will want much of the time?

**Comment by revgum** [comment]
if the value has been set, then set the option to selected for the appropriate language. 

Also, "create a blacklist of fields that do not have languages"

**Comment by straleyb** [comment]
This work was actually a 1, however, was dependent on a much larger feature which was multiple language support (13)
