### ISSUE TITLE
Remove Language on non-literal fields

### ISSUE THREAD

**Issue by wickr** [OregonDigital/ControlledVocabularyManager#143]
Since isReplacedBy should only be a URI, we don't need Language

**Comment by wickr** [comment]
Also isDefinedBy

**Comment by straleyb** [comment]
Effectively a 1 or 2. Created a blacklist and used that to dictate whether or not to render select fields. Can easily support new properties as time goes on. Still this was dependent on a much larger feature which was multiple language support. (13)
