### ISSUE TITLE
Fix spec for AllVocabsQuery, often failing locally when extra testing data exists

### ISSUE THREAD

**Issue by wickr** [OregonDigital/ControlledVocabularyManager#162]
`spec/queries/all_vocabs_query_spec.rb` will often fail locally if extra testing data has been added manually to Marmotta.

Specs are set up to use the 'test' context of Marmotta, but the spec uses sets up a SPARQL query that returns everything, using https://github.com/OregonDigital/ControlledVocabularyManager/blob/master/app/injectors/vocabulary_injector.rb#L15

To reproduce, create and persist Vocabularies and Terms manually via the console, then run tests.

Example error:

```
2) AllVocabsQuery.call when vocabularies exist should not return terms
     Failure/Error: expect(described_class.call(sparql_client, repository)).to eq [vocabulary]
       
       expected: [#<Vocabulary:0x3fd4262fec04(default)>]
            got: [#<Vocabulary:0x3fd4264d8f70(default)>, #<Vocabulary:0x3fd4264e11d4(default)>, #<Vocabulary:0x3fd4264e4c94(default)>, #<Vocabulary:0x3fd4264ecc00(default)>, #<Vocabulary:0x3fd4264f3000(default)>, #<Vocabulary:0x3fd4264fb37c(default)>, #<Vocabulary:0x3fd4265010b0(default)>, #<Vocabulary:0x3fd4265055e8(default)>, #<Vocabulary:0x3fd426510ee8(default)>, #<Vocabulary:0x3fd426514b88(default)>]
```

**Comment by straleyb** [comment]
This can be reproduced by ingesting a new vocabulary through the web form or by creating a new vocabulary through the console. Having an extra vocabulary in the database is what is causing this error.
