### ISSUE TITLE
When a new Term has spaces in the ID, it should give an error but return to Edit page saying ID was invalid

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/ControlledVocabularyManager#165]

**Comment by straleyb** [comment]
Currently, if you have any spaces in the term id, it sends the user to an ugly error page. This can substituted by sending the user back to the edit page saying their id was invalid. (Ex. Pepperoni Pizza)

**Comment by wickr** [comment]
If you try to create a new Term where the ID already exists, it does give you that error and takes you back to the form, so whatever is handling that can be copied or expanded to handle this issue.

**Comment by revgum** [comment]
relates to #181

**Comment by revgum** [comment]
Fixed in PR https://github.com/OregonDigital/ControlledVocabularyManager/pull/202
