### ISSUE TITLE
Hebrew language returns language not found

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/ControlledVocabularyManager#168]
When setting hebrew as a language and saving, it sets the value as language not found.

**Comment by wickr** [comment]
I just tried it on my local dev, and I see `(Language Not Found/iw)`  so it's saving 'iw' but not pulling the label.  'iw' shows up on the literal in the N-Triples output too.

**Comment by straleyb** [comment]
This was not fixed but is addressed in ticket #194.
