### ISSUE TITLE
When no Language is defined, don't display any Language info

### ISSUE THREAD

**Issue by wickr** [OregonDigital/ControlledVocabularyManager#171]
When no Language is set on a field, as in a lot of the existing data, the show page is currently displaying ` (Language Not Found/)`  and I think it shouldn't display anything.  Or if we want it to display something, more like `No Language Specified` and leave `Language Not Found` for more of an error message.

**Comment by revgum** [comment]
verified that this is no longer an issue, this was addressed by a previous PR related to default languages
