### ISSUE TITLE
Unicode character issues in saving and display

### ISSUE THREAD

**Issue by wickr** [OregonDigital/ControlledVocabularyManager#181]
http://opaquenamespace.org/ns/osuBuildings/C%EF%BF%BDsarCh%EF%BF%BDvezCulturalCenter

The accented characters were copied out of Word by me, so that might be part of the problem. Ideally we could handle that better though.

**Comment by revgum** [comment]
Need sanitization for ID's

**Comment by wickr** [comment]
Related to #165

**Comment by wickr** [comment]
Double check that Rails is set to UTF-8
