### ISSUE TITLE
Deprecate Vocabulary

### ISSUE THREAD

**Issue by wickr** [OregonDigital/ControlledVocabularyManager#184]
We have a way to deprecate Terms but it's not extended to Vocabularies.

**Comment by revgum** [comment]
"do you deprecate all of the terms in the vocab?" 
"should it check to see if there are active terms in the vocab and disallow?"

**Comment by wickr** [comment]
Candidates for deprecating: http://opaquenamespace.org/ns/TestVocabulary
Other terms that mistakenly got imported as Vocabularies but really aren't
