### ISSUE TITLE
Change tracking - integrate Git?

### ISSUE THREAD

**Issue by wickr** [OregonDigital/ControlledVocabularyManager#185]
We need a way to track who makes changes to Terms and what those changes are.

One option may be to integrate Git into the app, where a repo keeps a copy of the data and tracks changes that way. 
This gem should help with Git: https://github.com/libgit2/rugged  
So add a hook on each save to make a commit in Git as the user doing the save. This could then be pushed to GitHub as a backup. Once we build out Review/Approval queues, those could be handled in branches. We could also then pull in commit history from the Git repo and display that on Term pages, which may fulfill #183 . I don't envision needing to make changes directly to the Git repo, as it would be hard to sync back to the app.

Another option might be to use Changeset vocab and add triples to the record every time a change is made.
http://vocab.org/changeset/schema#ChangeSet
This is used lightly by LC at id.loc.gov

**Comment by lsat12357** [comment]
One difficulty with libgit2, which the rugged gem is built on, is that there is no easy way to track the commits for specific file; you have to use a walker: https://github.com/libgit2/rugged/issues/529
Depending on what information we want to grab from the commit history, we may have to walk all of the commits and test them. 
One solution is to store commit information at the time a term is created and updated. As an intermediate step in displaying commit information, we could provide a link to the term on github.
