### ISSUE TITLE
Language codes fail to save in marmotta properly. :he, :id, :yi

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/ControlledVocabularyManager#194]
These are the languages that are being translated when storing into marmotta. This is probably due to a change in the standard of ISO_639_1. We need to solve how to get them to stop translating to use them in the form.

**Comment by mickeroo** [comment]
This may not be an issue with Blazegraph

**Comment by revgum** [comment]
Confirmed this is not an issue with Blazegraph. Yiddish (yi), Hebrew (he), and Indosian (id) are persisted properly
