### ISSUE TITLE
Languages SELECT list order

### ISSUE THREAD

**Issue by revgum** [OregonDigital/ControlledVocabularyManager#215]
Currently appears to be ordered by the two letter language code, but needs to be ordered by the text of the language name.

**Comment by revgum** [comment]
app/views/vocabularies/_language_select.html.erb needs to have "sorted_language_list" instead of "language_list"

**Comment by wickr** [comment]
Fix included in https://github.com/OregonDigital/ControlledVocabularyManager/pull/226
