### ISSUE TITLE
List of Vocabularies that should be Predicates 

### ISSUE THREAD

**Issue by wickr** [OregonDigital/ControlledVocabularyManager#224]
Now that the Predicates type and page is up and working, we can move any Vocabularies that are really Predicates. The type URI gets changed via a SPARQL query, and I've been trying to also remove the old placeholder in rdfs:isDefinedBy: http://opaquenamespace.org/VOCAB_PLACEHOLDER.nt 

I moved a few already, but here is the proposed list of remaining Vocabularies to change:

### Change to Predicate

- [x] http://opaquenamespace.org/ns/conversionSpecifications
- [x] http://opaquenamespace.org/ns/tribalStatus
- [x] http://opaquenamespace.org/ns/coverDescription
- [x] http://opaquenamespace.org/ns/sourceCondition
- [x] http://opaquenamespace.org/ns/dateDigitized
- [x] http://opaquenamespace.org/ns/boxNumber
- [x] http://opaquenamespace.org/ns/boxName
- [x] http://opaquenamespace.org/ns/folderNumber
- [x] http://opaquenamespace.org/ns/localCollectionID
- [x] http://opaquenamespace.org/ns/canzonierePoems
- [x] http://opaquenamespace.org/ns/captionTitle
- [x] http://opaquenamespace.org/ns/compassDirection
- [x] http://opaquenamespace.org/ns/militaryHighestRank
- [x] http://opaquenamespace.org/ns/militaryServiceLocation
- [x] http://opaquenamespace.org/ns/militaryOccupation
- [x] http://opaquenamespace.org/ns/militaryBranch
- [x] http://opaquenamespace.org/ns/tgm
- [x] http://opaquenamespace.org/ns/rightsHolder
- [x] http://opaquenamespace.org/ns/tgn
- [x] http://opaquenamespace.org/ns/ethnographic
- [x] http://opaquenamespace.org/ns/awardDate
- [x] http://opaquenamespace.org/ns/artSeries
- [x] http://opaquenamespace.org/ns/tribalTitle
- [x] http://opaquenamespace.org/ns/tribalNotes
- [x] http://opaquenamespace.org/ns/tribalTerms
- [x] http://opaquenamespace.org/ns/tribalClasses
- [x] http://opaquenamespace.org/ns/seriesNumber
- [x] http://opaquenamespace.org/ns/llid
- [x] http://opaquenamespace.org/ns/folderName
- [x] http://opaquenamespace.org/ns/hydrologicUnitCode
- [x] http://opaquenamespace.org/ns/collectedDate
- [x] http://opaquenamespace.org/ns/specimenType
- [x] http://opaquenamespace.org/ns/objectOrientation
- [x] http://opaquenamespace.org/ns/photographOrientation

### Unsure

- [x] http://opaquenamespace.org/ns/terms - not sure what this was for. delete it?
- [x] http://opaquenamespace.org/ns/sportsTeam - maybe expand to have team names as
Terms here in the future? or make it a Predicate and use other term source (wikidata?)

**Comment by jsimic** [comment]
@wickr List looks good. Terms was an old version of subjects and can be deleted. I like making sportsTeam a predicate, as listed in the metadata dictionary, but imagine we'll also have to have a vocabulary at some point.

**Comment by wickr** [comment]
Thanks Julia. I deleted 'terms' and changed sportsTeam to a predicate.
All the others are completed too.
