### ISSUE TITLE
If we use Git as the "master copy" How do we sync from triple store

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/ControlledVocabularyManager#236]
If we make the git repo the master copy of the data and someone goes into sparql and updates a triple through said interface, the data would get out of sync. Do we want to use git as the master copy? Do we want to use a triple store context? I dont know. Some thought needs to go into this. 

How do we keep both of these in sync?

**Comment by revgum** [comment]
For now, we're not going to allow or provide means for bulk SPARQL updates to flow back through the app into the git repo. We need some sort of "bulk" update on the application side which would update git and the triplestore.

Ongoing, we treat git as the master data and the triplestore as an index essentially.
