### ISSUE TITLE
Define abilities for User Roles

### ISSUE THREAD

**Issue by wickr** [OregonDigital/ControlledVocabularyManager#242]
Here's what I propose for the User abilities. I see these as 'stacked' here, so a Reviewer can do what an Editor can, and an Admin can do what a Reviewer and Editor can. I can't think of a reason to do 'split' roles (person is Admin and Editor, but not Reviewer) but if someone has one please share.

Admin
- can Edit users and change roles
- can Approve Deprecation of Predicates and Vocabularies
- can Create new Vocabularies and Predicates (still reviewed by other Admin)
- can Approve others' new Vocabularies and Predicates

Reviewer
- can see Review queue and Approve changes to properties
- can Approve new Terms 
- can Approve Deprecation of Terms

Editor
- submit Edits to Terms, Vocabularies, Predicates
- can Create new Terms for review
- can see Review queue but not approve changes

**Comment by jsimic** [comment]
Looks good.

**Comment by straleyb** [comment]
Blocked by #35 approval queue. Most are about review.
