### ISSUE TITLE
Show last 3 Edits on Term/Vocabulary/Predicate show pages

### ISSUE THREAD

**Issue by wickr** [OregonDigital/ControlledVocabularyManager#246]
(Once the Git change tracking is in place. #185 )

On the main Term/Vocabulary/Predicate Show page, show the last 3 edits from the change history. This will likely change or tweak the current Issued/Modified date display.

Should include date (optionally time too, but probably not worth it for display), what property was changed, and who did it.

Something like:

#### Recent Changes
* 2016-02-15 - Comment changed, added "Additional notes about this term." (RW)
* 2015-11-23 - Label changed, from "Original Label" to "Longer and More Accurate Label" (JS)
* 2015-08-01 - Term created (RW)

For the user identification, I'm thinking initials is best, to identify people but not have full names or emails displayed everywhere. (If we have collisions with initials, maybe (First Name, Last Initial) or something). Those could link to a User profile page with email for contact info.

**Comment by jsimic** [comment]
Probably better to start with using a username rather than initials.

**Comment by wickr** [comment]
Ok. And the part of our email addresses before the '@' is sufficient for that? Otherwise we need to add a username field.

**Comment by jsimic** [comment]
I think so.

**Comment by lsat12357** [comment]
this isn't TOO ugly...

Recent changes:

2016-05-19 15:14:31 -0700
  deleted: <http://opaquenamespace.org/ns/mylittlevocab/yippykiyay> <http://www.w3.org/2000/01/rdf-schema#comment> "yoo hoo"@en . 
added: <http://opaquenamespace.org/ns/mylittlevocab/yippykiyay> <http://www.w3.org/2000/01/rdf-schema#comment> "yoo hoo hoo"@en . 
  admin

**Comment by wickr** [comment]
It'd be good to remove the subject URI from the display, since this should be on the show page already.

Having the full subject/predicate/object display makes more sense on a site-wide Recent Changes page I think.
