### ISSUE TITLE
README for Git directory

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/ControlledVocabularyManager#261]
Include information on why the local Git repo is there, and how it is used by the application.

**Comment by lsat12357** [comment]
Explain why the directory's there

**Comment by lsat12357** [comment]
this is for github opaquenamespace data

**Comment by lsat12357** [comment]
Opaquenamespace-data

This repository contains n-triples of the vocabularies, predicates, and terms that are served by <a href="http://opaquenamespace.org">opaquenamespace.org.</a>
The n-triples are generated when terms are created in the <a href = "http://github.com/OregonDigital/ControlledVocabularyManager">Controlled Vocabulary Manager,</a> and stored locally for production. Copies are routinely pushed up here.

**Comment by revgum** [comment]
added text to README.md in local repo, will make its way to github on next push
