### ISSUE TITLE
Diff view for approval queue

### ISSUE THREAD

**Issue by revgum** [OregonDigital/ControlledVocabularyManager#265]
One possible solution would be to use prettydiff on the client side to show the current production stringified ntriples and the stringified ntriples that are in the queue.

**Comment by lsat12357** [comment]
###experimenting with rugged in the console:

###part output from git log
commit ae2083854f18c14830abee1fcf8686330ebb91dd
Merge: 500e8cf 5bfd549
Author: admin <admin@example.org>
Date:   Wed May 18 14:36:42 2016 -0700

    Merge mylittlevocab/yippykiyay into master

commit 5bfd549aec94812c94a1a5458ae763974b0f2d4e
Author: admin <admin@example.org>
Date:   Wed May 18 14:36:42 2016 -0700

    updating: mylittlevocab/yippykiyay

commit 500e8cf8d9988edccd1bbb35ecaa7df3c866f2f0
Merge: dac3966 c770977
Author: admin <admin@example.org>
Date:   Wed May 18 13:06:31 2016 -0700

    Merge mylittlevocab/yippykiyay into master

commit c77097757794097fc1fa3dc53a3fb48c8241bed5
Author: admin <admin@example.org>
Date:   Wed May 18 13:06:31 2016 -0700

    creating: mylittlevocab/yippykiyay

##### in rails c
[11] controlled_vocabulary_manager »  thing1 = repo.lookup("c77097757794097fc1fa3dc53a3fb48c8241bed5")
[11] controlled_vocabulary_manager »  thing1 = repo.lookup("c77097757794097fc1fa3dc53a3fb48c8241bed5")
=> #<Rugged::Commit:69924937731600 {message: "creating: mylittlevocab/yippykiyay", tree: #<Rugged::Tree:69924937730280 {oid: 6e61d6d08e510a20b785d8a11d1dd31c72373982}>
  <"blip.nt" 125de9eaab1914aaf6d9067a94389fd53b6c2cb0>
  <"blip" f2fd6ceb2eb5c9b4a616dc948f5957e55fe0d793>
  <"mylittlevocab" 637a5546f5480851dca3931ffab9cbf220230934>
  <"readme" 907b308167f0880fb2a5c0e1614bb0c7620f9dc3>
[12] controlled_vocabulary_manager »  thing2 = repo.lookup("5bfd549aec94812c94a1a5458ae763974b0f2d4e")
[12] controlled_vocabulary_manager »  thing2 = repo.lookup("5bfd549aec94812c94a1a5458ae763974b0f2d4e")
=> #<Rugged::Commit:69924937660600 {message: "updating: mylittlevocab/yippykiyay", tree: #<Rugged::Tree:69924937659080 {oid: 64979d056ea3c01a1e072267109afc2f39dc55dc}>
  <"blip.nt" 125de9eaab1914aaf6d9067a94389fd53b6c2cb0>
  <"blip" f2fd6ceb2eb5c9b4a616dc948f5957e55fe0d793>
  <"mylittlevocab" 9092ff9cd5549ffbae719c3db874a2f2423d7a86>
  <"readme" 907b308167f0880fb2a5c0e1614bb0c7620f9dc3>
, parents: ["500e8cf8d9988edccd1bbb35ecaa7df3c866f2f0"]}>
[13] controlled_vocabulary_manager »  commits = thing1.diff(thing2)
=> #<Rugged::Diff:0x007f31562267b0 @owner=#<Rugged::Repository:69924938430700 {path: "/home/lsato/ControlledVocabularyManager/git_dev/.git/"}>>
[14] controlled_vocabulary_manager »  commits.patch

###output of commits.patch with newlines inserted for easier reading
=> "diff --git a/mylittlevocab/yippykiyay.nt b/mylittlevocab/yippykiyay.nt\nindex 1b3321f..0ded20e 100644\n--- a/mylittlevocab/yippykiyay.nt\n+++ b/mylittlevocab/yippykiyay.nt\n@@ -1 +1 @@\n
-<http://opaquenamespace.org/ns/mylittlevocab/yippykiyay> <http://purl.org/dc/terms/issued> \"2016-05-18\"^^<http://www.w3.org/2001/XMLSchema#date> . 
<http://opaquenamespace.org/ns/mylittlevocab/yippykiyay> <http://purl.org/dc/terms/modified> \"2016-05-18\"^^<http://www.w3.org/2001/XMLSchema#date> . 
<http://opaquenamespace.org/ns/mylittlevocab/yippykiyay> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2004/02/skos/core#CorporateName> . <http://opaquenamespace.org/ns/mylittlevocab/yippykiyay> <http://www.w3.org/2000/01/rdf-schema#label> \"yippi yip yip\"@en .\n\\ No newline at end of file\n

+<http://opaquenamespace.org/ns/mylittlevocab/yippykiyay> <http://purl.org/dc/terms/issued> \"2016-05-18\"^^<http://www.w3.org/2001/XMLSchema#date> . 
<http://opaquenamespace.org/ns/mylittlevocab/yippykiyay> <http://purl.org/dc/terms/modified> \"2016-05-18\"^^<http://www.w3.org/2001/XMLSchema#date> . 
<http://opaquenamespace.org/ns/mylittlevocab/yippykiyay> <http://schema.org/alternateName> \"yippieyappie\"@en . 
<http://opaquenamespace.org/ns/mylittlevocab/yippykiyay> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2004/02/skos/core#CorporateName> . <http://opaquenamespace.org/ns/mylittlevocab/yippykiyay> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2004/02/skos/core#Concept> . 
<http://opaquenamespace.org/ns/mylittlevocab/yippykiyay> <http://www.w3.org/2000/01/rdf-schema#label> \"yippi yip yip\"@en .\n\\ No newline at end of file\n"

**Comment by lsat12357** [comment]
just found a site that has some useful sample code. Adapted to the context started above:

commits = thing1.diff(thing2)
commits.each_patch { |patch|
  file = patch.delta.old_file[:path]

  patch.each_hunk { |hunk|
    hunk.each_line { |line|
      case line.line_origin
      when :addition
        puts "added: " + line.content
      when :deletion
        puts "deleted: " + line.content
      when :context
        #do nothing
      end
    }
  }
}

this pulls out the diffs pretty nicely, especially after I inserted newlines after the end of each triple before commiting it in git.
