### ISSUE TITLE
Change commit author in opaquenamespace-data

### ISSUE THREAD

**Issue by mickeroo** [OregonDigital/ControlledVocabularyManager#280]
During the initial load of terms/vocabs into Git (https://github.com/OregonDigital/opaquenamespace-data), Josh was listed as the owner.  Change that ownership info to a "generic" user with the DSC's email address.

**Comment by wickr** [comment]
Amended the author and message of the root commit. Pushed to GitHub, then pulled that down to the server and did a hard reset.
