### ISSUE TITLE
If a URI exists in a property, when editing the Term it shows as 'default'

### ISSUE THREAD

**Issue by wickr** [OregonDigital/ControlledVocabularyManager#307]
The 'default' label is displayed for a form field that is a URI. 'default' then gets saved as the value.

Related to #158

**Comment by revgum** [comment]
Could be the stringified name of the statement or graph.

**Comment by revgum** [comment]
Work is somewhat addressed on @luisgreg99 branch feature/EnableURI in the views I added the MaybeURI call to grab and use the URI.
