### ISSUE TITLE
Add approval queue for new terms

### ISSUE THREAD

**Issue by kestlund** [OregonDigital/ControlledVocabularyManager#35]
Terms should be approved by a metadata expert at each institution.

**Comment by wickr** [comment]
Should something record who reviewed a term?

**Comment by revgum** [comment]
Track who/when made the changes to the term?

**Comment by mickeroo** [comment]
We need to discuss this in greater detail and will create new tickets once we decide on the workflow

**Comment by srabun** [comment]
roles:
admin - can assign roles and review staff and student work, depricate terms
reviewer - can approve contributor  work, edit, submit, deprecate terms
contributor - can submit, edit, deprecate (must be reviewed)

when things are edited, it would be nice to know what had been changed in the record

What constitutes review?
Review = checking other vocabs
