### ISSUE TITLE
Terms not loading in Review

### ISSUE THREAD

**Issue by revgum** [OregonDigital/ControlledVocabularyManager#350]
For instance: http://opaquenamespace.org/review/people/HinriksdottirHallaMargret will not load

**Comment by wickr** [comment]
Also
http://opaquenamespace.org/review/people/LydiarttJayneM
http://opaquenamespace.org/review/osuBuildings/CentroCulturalCesarChavez
http://opaquenamespace.org/review/people/FuryRobert

**Comment by revgum** [comment]
see issues #356, #354, #353, #352
