### ISSUE TITLE
[cleanup] Terms being replaced with valid IDs

### ISSUE THREAD

**Issue by revgum** [OregonDigital/ControlledVocabularyManager#358]
Add terms in comments with the status of each so that we can track the progress of the cleanup in one spot

**Comment by luisgreg99** [comment]
`osuBuildings/CentroCulturalCï¿½sarChï¿½vez` replaced with `osuBuildings/CentroCulturalCesarChavez`

**Comment by revgum** [comment]
Here's the full list of Terms:

commonNames/California'sseahare.nt
commonNames/Cockerell'snudibranch.nt
creator/1+2Architecture.nt
creator/AchenbachArchitekten+Design.nt
creator/Bï¿½chlerPavel.nt
creator/Bury+Pittman.nt
creator/Carriï¿½nUlises.nt
creator/Carter+BurtonArchitecture.nt
creator/Carver+Schicketanz.nt
creator/Cï¿½netMichel.nt
creator/Dogbowl+BonesPublishing.nt
creator/DuvalAdï¿½le.nt
creator/FelipeAssadi+FranciscaPulidoArchitects.nt
creator/GendaiBijutsuSent?CCAKitakyushu.nt
creator/Haworth:OfficeExplorationsTeam.nt
creator/ï¿½lafurElï¿½asson1967.nt
creator/KnodelLarryREBeans).nt
creator/MoulyFranc?oise.nt
creator/OlbrichJï¿½rgenO.nt
creator/Olive1:1ResearchandDevelopment.nt
creator/PardinelSr?.nt
creator/Pugh+ScarpaArchitecture.nt
creator/RajivSaini+Associates.nt
creator/Shepherd+BoydUSA.nt
creator/Verso%2fICAPublications.nt
culture/SicÃ¡n.nt
culture/St.JohnsCulture.nt
genus/Cancersp..nt
genus/Haliotissp..nt
genus/Lithopomasp..nt
genus/Lopholithodessp..nt
genus/Pisastersp..nt
genus/Squatinasp..nt
localCollectionName/BarcelonaModernismeandGaudï¿½.nt
localCollectionName/R&amp;ELinkCollection.nt
localCollectionName/T.Waller.nt
osuBuildings/CentroCulturalCï¿½sarChï¿½vez.nt
people/Fernï¿½ndezNatalia.nt
people/LopezXavierXavi'.nt
people/MarquisLucian1921?2005.nt
publisher/JeanDominiqueCarrï¿½ArchivesLibrairie.nt
stylePeriod/Altai%2fArzhanPeriod.nt
stylePeriod/Altai%2fBronzeAgeandlater.nt
stylePeriod/Altai%2fBronzeAgetoModern.nt
stylePeriod/Altai%2fEarlyIronAgeorlater.nt
stylePeriod/Altai%2fEarlyNomadic.nt
stylePeriod/Altai%2fEthnographicPeriod.nt
stylePeriod/Altai%2fKyrgyz.nt
stylePeriod/Altai%2flate.nt
stylePeriod/Altai%2fLatePazyryk.nt
stylePeriod/Altai%2fMongolPeriod.nt
stylePeriod/Altai%2fmorerecent.nt
stylePeriod/Altai%2fpossiblylater.nt
stylePeriod/Altai%2fPostTurkic.nt
stylePeriod/Altai%2fPreBronzeAge.nt
stylePeriod/Altai%2fPreModern.nt
stylePeriod/Altai%2frecent.nt
stylePeriod/Altai%2fTamga.nt
stylePeriod/Altai%2fTurkicPeriod.nt
stylePeriod/Altai%2fUighurPeriod.nt
stylePeriod/Altai%2funcertain.nt
stylePeriod/Altai%2fvaried.nt
stylePeriod/People'sRepublicofChina.nt
stylePeriod/St.Johns.nt
subject/Anseriformes(waterfowl)-mergansers.nt
subject/Anseriformes(waterfowl)-seaducks.nt
subject/Anseriformes(waterfowl)-surfacefeedingducks.nt
subject/Charadriiformes(shorebirds,gulls,alcids)-Scalopacidae(sandpipers).nt
subject/KLIVRadiostation:SanJoseCalif.nt
subject/Pelecaniformes(pelicansandallies)-Frigatidae(frigatebirds).nt
subject/Urochordata:AppendiculariaorLarvacea.nt
technique/artistsbooks%2fother.nt
TestVocabulary/ï¿½ï¿½ï¿½.nt
workType/Altai%2fbalbal.nt
workType/Altai%2fboulderkhirigsuur.nt
workType/Altai%2fcircularaltars.nt
workType/Altai%2fcollaredmounds.nt
workType/Altai%2fdeerstones.nt
workType/Altai%2fdoublemounds.nt
workType/Altai%2fdwellings.nt
workType/Altai%2fenclosures.nt
workType/Altai%2fextendedlinearfeatures.nt
workType/Altai%2ffalsedeerstones.nt
workType/Altai%2ffalseimagestones.nt
workType/Altai%2ffourcorneredmounds.nt
workType/Altai%2fframes.nt
workType/Altai%2fimagestonesBronzeAge.nt
workType/Altai%2finscriptions.nt
workType/Altai%2fkeyholemounds.nt
workType/Altai%2fkhirigsuur.nt
workType/Altai%2flargecircles.nt
workType/Altai%2fmassivestandingstones.nt
workType/Altai%2fmoderngraves.nt
workType/Altai%2fmoundsunknownuse.nt
workType/Altai%2fovoooboo.nt
workType/Altai%2fperiodoverlays.nt
workType/Altai%2fpetroglyphs.nt
workType/Altai%2fplatformkhirigsuur.nt
workType/Altai%2frays.nt
workType/Altai%2frectangularmounds.nt
workType/Altai%2fritualmounds.nt
workType/Altai%2fritualsites.nt
workType/Altai%2froundkhirigsuur.nt
workType/Altai%2fsemicircles.nt
workType/Altai%2fserpentinefeatures.nt
workType/Altai%2fsmallcircularaltars.nt
workType/Altai%2fsquarekhirigsuur.nt
workType/Altai%2ftamga.nt
workType/Altai%2fTurkicimagestones.nt
workType/Altai%2fUighurimages.nt
workType/Altai%2fviewsofcomplexesorgroupings.nt

**Comment by revgum** [comment]
There are 5 PR's on opaquenamespace-data repo to address these terms with invalid IDs, the following list are the terms left that may need more consideration for how to replace:

creator/Bï¿½chlerPavel.nt
creator/Carriï¿½nUlises.nt
creator/Cï¿½netMichel.nt
creator/DuvalAdï¿½le.nt
creator/GendaiBijutsuSent?CCAKitakyushu.nt
creator/ï¿½lafurElï¿½asson1967.nt
creator/KnodelLarryREBeans).nt
creator/MoulyFranc?oise.nt
creator/OlbrichJï¿½rgenO.nt
creator/PardinelSr?.nt
culture/SicÃ¡n.nt
culture/St.JohnsCulture.nt
localCollectionName/BarcelonaModernismeandGaudï¿½.nt
localCollectionName/R&amp;ELinkCollection.nt
localCollectionName/T.Waller.nt
osuBuildings/CentroCulturalCï¿½sarChï¿½vez.nt
people/Fernï¿½ndezNatalia.nt
people/MarquisLucian1921?2005.nt
publisher/JeanDominiqueCarrï¿½ArchivesLibrairie.nt
stylePeriod/St.Johns.nt
subject/Anseriformes(waterfowl)-mergansers.nt
subject/Anseriformes(waterfowl)-seaducks.nt
subject/Anseriformes(waterfowl)-surfacefeedingducks.nt
subject/Charadriiformes(shorebirds,gulls,alcids)-Scalopacidae(sandpipers).nt
subject/Pelecaniformes(pelicansandallies)-Frigatidae(frigatebirds).nt
TestVocabulary/ï¿½ï¿½ï¿½.nt

**Comment by revgum** [comment]
See opaquenamespace-data repo PR #7 (https://github.com/OregonDigital/opaquenamespace-data/pull/7) for proposed updates.
- `creator/KnodelLarryREBeans).nt` can be deleted, it has a duplicate without the right-parens
- `creator/GendaiBijutsuSent?CCAKitakyushu.nt` : Replace ? with _
- `creator/MoulyFranc?oise.nt` : Remove ?
- `creator/PardinelSr?.nt` : Remove ?
- `culture/SicÃ¡n.nt` : Replace Ã¡ with a
- `culture/St.JohnsCulture.nt` : Remove .
- `localCollectionName/R&ELinkCollection.nt` : Replace & with -
- `localCollectionName/T.Waller.nt` : Replace . with -
- `people/MarquisLucian1921?2005.nt` : Replace ? with -
- `stylePeriod/St.Johns.nt` : Remove .

The remaining are `subject/*` with parenthesis and commas, or with the `ï¿½`. 

`ï¿½` could be replaced with a character and that would address many of the remaining Terms.

**Comment by jsimic** [comment]
The ï¿½ does not seem to be a consistent character between entries. Some times o umlaut, sometimes, i acute, etc. Might have to do those by hand.

**Comment by jsimic** [comment]
creator/Bï¿½chlerPavel.nt : replace with u
creator/Carriï¿½nUlises.nt : replace with o
creator/GendaiBijutsuSent?CCAKitakyushu.nt : replace with a
creator/ï¿½lafurElï¿½asson1967.nt : replace with O and i
creator/OlbrichJï¿½rgenO.nt : replace with u
localCollectionName/BarcelonaModernismeandGaudï¿½.nt : replace with i
osuBuildings/CentroCulturalCï¿½sarChï¿½vez.nt : replace with e and a
people/Fernï¿½ndezNatalia.nt : replace with a
publisher/JeanDominiqueCarrï¿½ArchivesLibrairie.nt : replace with e
stylePeriod/St.Johns.nt : drop .

That leaves 2 to track down tomorrow:
creator/Cï¿½netMichel.nt
creator/DuvalAdï¿½le.nt

**Comment by revgum** [comment]
Thanks @jsimic! I think the final terms we have left are:

subject/Anseriformes(waterfowl)-mergansers.nt
subject/Anseriformes(waterfowl)-seaducks.nt
subject/Anseriformes(waterfowl)-surfacefeedingducks.nt
subject/Charadriiformes(shorebirds,gulls,alcids)-Scalopacidae(sandpipers).nt
subject/Pelecaniformes(pelicansandallies)-Frigatidae(frigatebirds).nt

We need to replace the parenthesis and commas.. I feel like maybe we should remove the text in the parenthesis all together and leave that detail in the label or comment triples or something?

**Comment by wickr** [comment]
Clean list of new terms added to git so far, from merging the PRs in the opaquenamespace-data repo.

creator/12Architecture.nt
creator/AchenbachArchitektenDesign.nt
creator/BuchlerPavel.nt
creator/BuryPittman.nt
creator/CarrioUlises.nt
creator/CarterBurtonArchitecture.nt
creator/CarverSchicketanz.nt
creator/CenetMichel.nt
creator/DogbowlBonesPublishing.nt
creator/DuvalAdele.nt
creator/FelipeAssadiFranciscaPulidoArchitects.nt
creator/GendaiBijutsuSentaCCAKitakyushu.nt
creator/Haworth-OfficeExplorationsTeam.nt
creator/MoulyFrancoise.nt
creator/OlafurEliasson1967.nt
creator/OlbrichJurgenO.nt
creator/Olive1-1ResearchandDevelopment.nt
creator/PardinelSr.nt
creator/PughScarpaArchitecture.nt
creator/RajivSainiAssociates.nt
creator/ShepherdBoydUSA.nt
creator/Verso-ICAPublications.nt
culture/Sican.nt
culture/StJohnsCulture.nt
genus/Cancer.nt
genus/Haliotis.nt
genus/Lithopoma.nt
genus/Lopholithodes.nt
genus/Pisaster.nt
genus/Squatina.nt
localCollectionName/BarcelonaModernismeandGaudi.nt
localCollectionName/R-ELinkCollection.nt
localCollectionName/T-Waller.nt
people/FernandezNatalia.nt
people/KamalaniKeloni.nt
people/LopezXavierXavi.nt
people/MarquisLucian1921-2005.nt
publisher/JeanDominiqueCarreArchivesLibrarie.nt
stylePeriod/Altai-ArzhanPeriod.nt
stylePeriod/Altai-BronzeAgeandlater.nt
stylePeriod/Altai-BronzeAgetoModern.nt
stylePeriod/Altai-EarlyIronAgeorlater.nt
stylePeriod/Altai-EarlyNomadic.nt
stylePeriod/Altai-EthnographicPeriod.nt
stylePeriod/Altai-Kyrgyz.nt
stylePeriod/Altai-LatePazyryk.nt
stylePeriod/Altai-MongolPeriod.nt
stylePeriod/Altai-PostTurkic.nt
stylePeriod/Altai-PreBronzeAge.nt
stylePeriod/Altai-PreModern.nt
stylePeriod/Altai-Tamga.nt
stylePeriod/Altai-TurkicPeriod.nt
stylePeriod/Altai-UighurPeriod.nt
stylePeriod/Altai-late.nt
stylePeriod/Altai-morerecent.nt
stylePeriod/Altai-possiblylater.nt
stylePeriod/Altai-recent.nt
stylePeriod/Altai-uncertain.nt
stylePeriod/Altai-varied.nt
stylePeriod/PeoplesRepublicofChina.nt
stylePeriod/StJohns.nt
subject/KLIVRadiostation-SanJoseCalif.nt
subject/Urochordata-AppendiculariaorLarvacea.nt
technique/artistsbooks-other.nt
technique/hingedbinding.nt
workType/Altai-Turkicimagestones.nt
workType/Altai-Uighurimages.nt
workType/Altai-balbal.nt
workType/Altai-boulderkhirigsuur.nt
workType/Altai-circularaltars.nt
workType/Altai-collaredmounds.nt
workType/Altai-deerstones.nt
workType/Altai-doublemounds.nt
workType/Altai-dwellings.nt
workType/Altai-enclosures.nt
workType/Altai-extendedlinearfeatures.nt
workType/Altai-falsedeerstones.nt
workType/Altai-falseimagestones.nt
workType/Altai-fourcorneredmounds.nt
workType/Altai-frames.nt
workType/Altai-imagestonesBronzeAge.nt
workType/Altai-inscriptions.nt
workType/Altai-keyholemounds.nt
workType/Altai-khirigsuur.nt
workType/Altai-largecircles.nt
workType/Altai-massivestandingstones.nt
workType/Altai-moderngraves.nt
workType/Altai-moundsunknownuse.nt
workType/Altai-ovoooboo.nt
workType/Altai-periodoverlays.nt
workType/Altai-petroglyphs.nt
workType/Altai-platformkhirigsuur.nt
workType/Altai-rays.nt
workType/Altai-rectangularmounds.nt
workType/Altai-ritualmounds.nt
workType/Altai-ritualsites.nt
workType/Altai-roundkhirigsuur.nt
workType/Altai-semicircles.nt
workType/Altai-serpentinefeatures.nt
workType/Altai-smallcircularaltars.nt
workType/Altai-squarekhirigsuur.nt
workType/Altai-tamga.nt
workType/Altai-viewsofcomplexesorgroupings.nt

**Comment by wickr** [comment]
Old terms have been deleted from Blazegraph. A reindex was done. Affected vocabulary HTML pages have been removed so on next access they will be fresh.

The 5 terms in Josh's last comment had already been deprecated manually.
