### ISSUE TITLE
Invalid predicate URI for alternate name for certain terms

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/ControlledVocabularyManager#359]
One example is http://opaquenamespace.org/ns/workType/Altai/tamga

Its not displaying the alternate name because its an invalid predicate uri

https://github.com/OregonDigital/opaquenamespace-data/blob/master/workType/Altai%252ftamga.nt#L8

(https:// instead of http://)

**Comment by revgum** [comment]
Here are the statements with https

<http://opaquenamespace.org/ns/workType/Altai/Turkicimagestones> <https://schema.org/alternateName> "Turkic image stone"@en .
<http://opaquenamespace.org/ns/workType/Altai/Uighurimages> <https://schema.org/alternateName> "Uighur image"@en .
<http://opaquenamespace.org/ns/workType/Altai/balbal> <https://schema.org/alternateName> "balbals"@en .
<http://opaquenamespace.org/ns/workType/Altai/boulderkhirigsuur> <https://schema.org/alternateName> "boulder khirigsuurs"@en .
<http://opaquenamespace.org/ns/workType/Altai/circularaltars> <https://schema.org/alternateName> "circular altar"@en .
<http://opaquenamespace.org/ns/workType/Altai/collaredmounds> <https://schema.org/alternateName> "collared mound"@en .
<http://opaquenamespace.org/ns/workType/Altai/deerstones> <https://schema.org/alternateName> "deer stone"@en .
<http://opaquenamespace.org/ns/workType/Altai/doublemounds> <https://schema.org/alternateName> "double mound"@en .
<http://opaquenamespace.org/ns/workType/Altai/dwellings> <https://schema.org/alternateName> "dwelling"@en .
<http://opaquenamespace.org/ns/workType/Altai/enclosures> <https://schema.org/alternateName> "enclosure"@en .
<http://opaquenamespace.org/ns/workType/Altai/extendedlinearfeatures> <https://schema.org/alternateName> "lines"@en .
<http://opaquenamespace.org/ns/workType/Altai/falsedeerstones> <https://schema.org/alternateName> "false deer stone"@en .
<http://opaquenamespace.org/ns/workType/Altai/falseimagestones> <https://schema.org/alternateName> "false image stone"@en .
<http://opaquenamespace.org/ns/workType/Altai/fourcorneredmounds> <https://schema.org/alternateName> "four-cornered mound"@en .
<http://opaquenamespace.org/ns/workType/Altai/frames> <https://schema.org/alternateName> "frame"@en .
<http://opaquenamespace.org/ns/workType/Altai/imagestonesBronzeAge> <https://schema.org/alternateName> "image stone, Bronze Age"@en .
<http://opaquenamespace.org/ns/workType/Altai/inscriptions> <https://schema.org/alternateName> "inscription"@en .
<http://opaquenamespace.org/ns/workType/Altai/keyholemounds> <https://schema.org/alternateName> "key-hole mound"@en .
<http://opaquenamespace.org/ns/workType/Altai/khirigsuur> <https://schema.org/alternateName> "khirigsuurs"@en .
<http://opaquenamespace.org/ns/workType/Altai/largecircles> <https://schema.org/alternateName> "large circle"@en .
<http://opaquenamespace.org/ns/workType/Altai/massivestandingstones> <https://schema.org/alternateName> "massive standing stone"@en .
<http://opaquenamespace.org/ns/workType/Altai/moderngraves> <https://schema.org/alternateName> "modern grave"@en .
<http://opaquenamespace.org/ns/workType/Altai/moundsunknownuse> <https://schema.org/alternateName> "mound-unknown use"@en .
<http://opaquenamespace.org/ns/workType/Altai/ovoooboo> <https://schema.org/alternateName> "ovoos/oboos"@en .
<http://opaquenamespace.org/ns/workType/Altai/periodoverlays> <https://schema.org/alternateName> "period overlay"@en .
<http://opaquenamespace.org/ns/workType/Altai/petroglyphs> <https://schema.org/alternateName> "petroglyph"@en .
<http://opaquenamespace.org/ns/workType/Altai/platformkhirigsuur> <https://schema.org/alternateName> "platform khirigsuurs"@en .
<http://opaquenamespace.org/ns/workType/Altai/rays> <https://schema.org/alternateName> "ray"@en .
<http://opaquenamespace.org/ns/workType/Altai/rectangularmounds> <https://schema.org/alternateName> "rectangula rmound"@en .
<http://opaquenamespace.org/ns/workType/Altai/ritualmounds> <https://schema.org/alternateName> "ritual mound"@en .
<http://opaquenamespace.org/ns/workType/Altai/ritualsites> <https://schema.org/alternateName> "ritual site"@en .
<http://opaquenamespace.org/ns/workType/Altai/roundkhirigsuur> <https://schema.org/alternateName> "round khirigsuurs"@en .
<http://opaquenamespace.org/ns/workType/Altai/semicircles> <https://schema.org/alternateName> "semi-circle"@en .
<http://opaquenamespace.org/ns/workType/Altai/serpentinefeatures> <https://schema.org/alternateName> "serpentine feature"@en .
<http://opaquenamespace.org/ns/workType/Altai/smallcircularaltars> <https://schema.org/alternateName> "small circular altar"@en .
<http://opaquenamespace.org/ns/workType/Altai/squarekhirigsuur> <https://schema.org/alternateName> "square khirigsuurs"@en .
<http://opaquenamespace.org/ns/workType/Altai/viewsofcomplexesorgroupings> <https://schema.org/alternateName> "view of complexes or groupings"@en .
<http://opaquenamespace.org/ns/people/KamalaniKeloni> <https://schema.org/alternateName> "Kamalani, Keloni Kimo Logan Sarasin"@en .
<http://opaquenamespace.org/ns/technique/hingedbinding> <https://schema.org/alternateName> "crossed structure binding"@en .
cd

**Comment by revgum** [comment]
Wow, that's not 100% useful..

**Comment by revgum** [comment]
The Altai* terms are being replaced with new terms having proper IDs in PR #1 on the opaquenamespace-data repo. The remaining two terms are updated in PR#6 on the opaquenamespace-data repo.
