### ISSUE TITLE
Make things static where possible

### ISSUE THREAD

**Issue by jechols** [OregonDigital/ControlledVocabularyManager#376]
For the .nt and json-ld views, unrelated app failures can lead to external fetching not working.  But if we set up nginx to just serve up static files instead of passing those to Rails, it's possible that fetching could continue to work no matter what's going on with the Rails side.

This would require generating static .nt and json-ld files every time things are created, reviewed, etc.  But it may be very worthwhile to give Oregon Digital (and other fetchers) a better uptime guarantee, as well as likely improving performance.

**Comment by revgum** [comment]
Ideally we could do this for the html views as well.

Either way, the vocabulary which a child term is part of will need to be rendered when a child term is created/updated (as part of the mark_reviewed action) because the vocabulary graphs include all of the children within.
