### ISSUE TITLE
Tombstone Vocabularies

### ISSUE THREAD

**Issue by wickr** [OregonDigital/ControlledVocabularyManager#38]
e.g. Don't delete but serve some message that says I've been deleted

**Comment by terrellt** [comment]
@kestlund What's the details on how this should work? What's the use case?

**Comment by wickr** [comment]
Possible use case: We add a local name to Creators, then that gets added to LCNAF or similar, and we want to use that instead.

**Comment by wickr** [comment]
Related to #38

**Comment by kestlund** [comment]
@wickr: has that use case correct. We want it to resolve on our site but point to the new place.

**Comment by terrellt** [comment]
@kestlund This isn't some status code that says "we deleted this"?

**Comment by kestlund** [comment]
@terrellt It should be some status that displays to the user when they go to the URL: "This is deprecated."  It should also optionally allow the redirect to either another site as @wickr describes for the other term, if possible vs. #39 where it is superseded by our own new version.
