### ISSUE TITLE
URI's not being handled correctly in CVM

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/ControlledVocabularyManager#402]
When you have a URI such as <http://opaquenamespace.org/ns/blah>, in git it gets added both as a string and as a uri. When it gets rendered on the show page of a term/vocabulary, it is also displaying the request object for that uri. (i.e `{:scheme=>"http", :authority=>"opaquenamespace.org", :userinfo=>nil, :user=>nil, :password=>nil, :host=>"opaquenamespace.org", :port=>nil, :path=>"/ns/TestVocabulary", :query=>nil, :fragment=>nil}`)

**Comment by wickr** [comment]
Try looking in Git data or triplestore for terms such as 'scheme' or 'authority' that shouldn't be there.

**Comment by straleyb** [comment]
The URI of the vocabulary gets copied into the subpropertyOf field. Also some fields seem to be dropping.

<img width="992" alt="screen shot 2018-05-10 at 1 54 24 pm" src="https://user-images.githubusercontent.com/6424683/39893787-bc7a80b0-5459-11e8-96dc-ac032bc70230.png">

**Comment by straleyb** [comment]
Doesnt break apart the vocab included. Just the one added. And only in the subpropertyOf field.

**Comment by straleyb** [comment]
<img width="1088" alt="screen shot 2018-05-10 at 2 07 18 pm" src="https://user-images.githubusercontent.com/6424683/39894382-7b64c566-545b-11e8-9383-02a6ce199220.png">

This was using a legit Vocabulary URI in my local instance of CVM

**Comment by straleyb** [comment]
Fixed by #548
