### ISSUE TITLE
On Create Term page, add button to drop in generated opaque ID to Term ID field

### ISSUE THREAD

**Issue by wickr** [OregonDigital/ControlledVocabularyManager#409]
On the Create Term page, next to the ID field, add a button that will fill-in the ID with an opaque identifier generated by the method in #408

**Comment by revgum** [comment]
Consider pre-filling the id with one generated server-side, but then allowing user to change it on the form field if they want a specific id.

**Comment by wickr** [comment]
@revgum yeah, I was initially thinking don't mix ID types in Vocabularies that aren't using opaque ones (Creators, Subjects, etc), so I wouldn't have it default to opaque for any new terms. But in the long run it's probably not a big deal since most other sources are using opaque IDs and like you said there'd still be an option.

@jsimic @sseymore or others does Josh's comment sound good?

**Comment by jsimic** [comment]
@wickr I like Josh's idea--maximum flexibility.
