### ISSUE TITLE
Add form hint text in form partials, adjust CSS as needed

### ISSUE THREAD

**Issue by wickr** [OregonDigital/ControlledVocabularyManager#455]
Expose form hint text using the form partials, also use i18n keys for field text. Some CSS may need adjusted, such as for ID (shrink vertical height of fixed vocab section, add some padding).

Adding `  <%= f.hint 'This ID was system generated, but can be overridden.' %>` 
to `_form_id.html.erb` renders as:

![screenshot from 2018-05-03 13-04-40](https://user-images.githubusercontent.com/2293544/39600291-267c1d16-4ed3-11e8-852e-1a9c220a527e.png)

If form field i18n keys are not added, don't

**Comment by straleyb** [comment]
Any other hints we would like to add for fields? Or just the id field?

**Comment by wickr** [comment]
Nothing else is ready to go yet, but we'll want the ability to added to the other fields, though I think it's just the 1 other partial that will handle them all. ID was the one with it's own specific partial.
