### ISSUE TITLE
Figure out, if using lunr, how we want to build the index.

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/ControlledVocabularyManager#502]
If we are using lunr, which seems like a possible option, we need to figure out how we want to build the index for lunr to use. We could rig it up to build it when something gets reviewed, or run it manually from the command line. 

It may take more or less work depending on what we decide. Command line will be easier, but will require a dev to go in and run the script. 

We can automate it, but that would take extra time for implementation.

**Comment by wickr** [comment]
This is no longer needed due to #509
