### ISSUE TITLE
About Lunr

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/ControlledVocabularyManager#504]
This is a ticket where I layout what I have learned about Lunr. 

Lunr is an interesting client side based search library, that can search a prebuilt index, or index that gets built on the fly. This is meant to be an offline search that doesnt need to be backed by something like Solr or any other index that requires an online connection. 

Since this is on offline index, the index is built every time someone visits the page. This is good for smaller indexes, but not as good for bigger indexes. One thing you can do to lower the amount of time it takes to build the index is to pre-generate the index. This means serving up the index every time from the file system to the user then loading the index into lunr which would do the searching. 

Close attention to detail will need to be had when pre-generating the index, and the data will have to be refined a bit to make sure everything including special characters are searchable, like enabling utf-8. 

One thing I have noticed that is odd, is the generation of the index. I generated an index, but it doesnt seem to be functioning correctly. Ill have to dig into this a bit more to get this working fully, but for now, all the javascript and things are working as expected. 

Do I think this is a viable option? Possibly. I havent tested larger indexes, and I havent gotten a fairly small index working yet. But once all the code is established, and we have an automated way to generate the indexes, it may be a good option. I really dont like having to serve up the index everytime someone visits the search page, and there does have to be a whole separate search area to get it working, since you have to run some specific javascript, and serve up a file. And the "Offline" searching becomes more of a gimmick rather than anything. But its fairly light weight and doesnt need much work to integrate into the system. It seems like a viable solution as long as the "Full index" of CVM getting served up isnt too big to serve and load into lunr.

**Comment by wickr** [comment]
Decided to go with Sunspot/Solr in #509
