### ISSUE TITLE
About sunspot

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/ControlledVocabularyManager#506]
Sunspot is an interesting gem. It uses solr as an indexing service and creates its own index based on a configuration on the object that it is on. Within the description of each index field, you can configure the field to map to whatever values you want, so you have plenty of control over the values being indexed. This is also really quite readable so its easy to see whats happening at a glance. It also provides a really nice and readable interface to do much more complicated things with solr, like weighting of values depending on specific matches, restrictions, conjunctions, pagination and many other things. This makes it easy to configure a full powered application with solr as an indexing service. Its also fairly light weight as far as a gem goes and doesnt have too much extra stuff built into it. This makes for less of a burden when integrating into an application.

One thing I have noticed, however, is that is tightly coupled based on the database that the application is backed by. It uses an adaptor to interface with said backend. By default, Sunspot is tightly coupled with active record in the sense that it ties into many backend calls for automation of indexing and updated the index based on the model being deleted or updated or ingested in general. In particular it uses #after_save and #before_save and #after_destroy, to automate the updating of the index. You can disable it, but it also uses another particular, which is #includes. https://apidock.com/rails/ActiveRecord/QueryMethods/includes . This method helps with dealing with relationships between objects, and making database queries a little more optimized. 

The issue with this, is that these methods arent included in ActiveTriples::Resource, which is the backend that we are using to power CVM. Instead, ActiveTriples uses #after_persist and #before_persist. This means there is a disconnect between the interface that sunspot is expecting and what the application is expecting. This means, it cant flow through the app naturally when indexing the information from the database into solr. 

This issue can be fixed by making an adapter in the application that you can make sunspot use. https://github.com/sunspot/sunspot/blob/master/sunspot_rails/lib/sunspot/rails/adapters.rb This is the adapter that sunspot uses to connect to activerecord directly. It follows the activerecord interface when calling the database and transforms the data into something sunspot can index into solr. We could write our own adapter to connect sunspot to active triples, but that would be extra development time. 

There may be something to bypass this, but i havent quite figured it out yet. Ill continue to see if there is some way to bypass sunspot expecting a database to index from the database into solr, but im not sure its entirely possible. There have been folks who made adapters for mongoid and others, but none for active triples.

**Comment by wickr** [comment]
Implemented Sunspot without the sunspot_rails gem in #509
