### ISSUE TITLE
List of questions surrounding URI issue

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/ControlledVocabularyManager#547]
- Which fields are meant to ONLY contain strings? - now shown in the MAP
- Which fields are meant to ONLY contain URIs - now shown in the MAP
- Which fields can have a mix of URIs and Strings? - none
- How does a triple look for something thats a URI in git?
`<http://opaquenamespace.org/ns/creator/OuthankKarlW> <http://purl.org/dc/terms/isReplacedBy> <http://id.loc.gov/authorities/names/no2016019608>`  (modified object to be a URI, that specific triple had it saved as a string)
- How does a triple look for something that is a string in git?
`<http://opaquenamespace.org/ns/localCollectionName/rg_250> <http://www.w3.org/2000/01/rdf-schema#label> "Difference, Power, and Discrimination Program Records (RG 250)"@en`
- How should BG interpret URIs? - it shouldn't do any interpreting
- Should we circle around and check if BG is functioning as we need it to? - I think it is functioning as we need it
- How should the system deal with URIs? For BG? For Git? - the value should always stay as a URI, it should not ever be saved or converted to a string/literal
- Should any uri's be supported or no? - yes

**Comment by wickr** [comment]
Closing this since the questions have been answered above.
