### ISSUE TITLE
Get vocabulary view and form showing all desired properties

### ISSUE THREAD

**Issue by jechols** [OregonDigital/ControlledVocabularyManager#58]
But... do we want all properties shown?  Just title and publisher?  (That's what OD's JSONLD terms use)  Is the form going to be using the same properties as the view?

**Comment by terrellt** [comment]
@jsimic My thought is to just make all properties show and be editable. Is there a problem with that?

**Comment by jechols** [comment]
I think we need to figure out (a) if terms have the same properties as vocabs (right now they have no choice but to do that), and if not, what properties we consider essential to vocabs.  I could see us adding half a dozen properties to terms, but not necessarily wanting those same things at the vocab level.

If we want them to share, we should consider whether we're *currently* doing it right.  All that JSONLD seems to suggest we didn't want them to share (terms use label and comment; vocabs use title and publisher).

**Comment by jsimic** [comment]
I'd prefer everything be shown/editable
