### ISSUE TITLE
Content Negotiation No Longer Working for OpaqueNamespace.org

### ISSUE THREAD

**Issue by markpbaggett** [OregonDigital/ControlledVocabularyManager#590]
**Describe the bug**

I'm not sure if this is an issue with the ControlledVocabularyManager, the web server opaquenamespace.org is installed on, or blazegraph, but traditionally I've been able to negotiate for RDF via standard content negotiation when I query URIs for properties at opaquenamespace.org.  As of this morning, this was no longer the case. No matter what I put in my accept headers, opaquenamespace.org seems to only return text/html. I'm not sure if this is a bug or a decision to no longer support content negotiation. 

Also, I apologize if I'm submitting this to the wrong place.

**To Reproduce**

``` python
import requests
headers = {
            "Accept": "text/turtle, application/turtle, application/x-turtle, application/json, text/json, text/n3,"
            "text/rdf+n3, application/rdf+n3, application/rdf+xml, application/n-triples"
        }
requests.get('http://opaquenamespace.org/ns/sheetmusic_hostItem', headers=headers)
print(r.headers['Content-Type'])
```

This prints `text/html`

If you ask for the content of the request, it's the HTML DOM.

**Expected behavior**
Historically, this has returned the RDF for the property (I think as n-triples, but I don't remember). This isn't necessarily a problem, but in my institution's RDF property selection criteria, we've historically required that the property not only be dereferenceable but also be content negotiable.  We're thinking about using a few specific properties from opaquenamespace.org and was curious whether this was a known issue.  

Again, apologies if this has nothing to do with the Ruby app.

**Comment by wickr** [comment]
Hi Mark, thanks for filing this. I had been forwarded your email and began to look into this. We recently did some server changes and we might have missed something with content negotiation. I hope to have this fixed very soon.

**Comment by markpbaggett** [comment]
@wickr sorry for sending that two places.  I regretfully sent an email before I found the repo / issue tracker.  Thanks for your help.

**Comment by wickr** [comment]
@markpbaggett no worries, I appreciated you raising it and also the detail in your message.

We made some updates on the server and content negotiation should work again. With your example I'm seeing this returned now: `application/n-triples; charset=utf-8`
Please confirm when you have a chance.

The only 2 formats we have directly activated are `application/n-triples` and `application/ld+json`

**Comment by markpbaggett** [comment]
@wickr, this is perfect!  Thanks again.

Closing.
