### ISSUE TITLE
Implement Search in CVM

### ISSUE THREAD

**Issue by wickr** [OregonDigital/ControlledVocabularyManager#70]

**Comment by revgum** [comment]
Need to investigate what (if any) work has already been done to start implementing the infrastructure to support search. Marmotta, Solr, etc? 

"search for terms, like person, which could be found in multiple vocabs"

**Comment by vantuyls** [comment]
At least want to be able to search for terms, vocabs, labels, and comments.  Still needs to be scoped and broken down.

**Comment by jsimic** [comment]
Would be nice to be able to search on labels, comments and type and combinations thereof. And have the option of searching a single or across vocabularies.

**Comment by wickr** [comment]
Resolved with #509
