### ISSUE TITLE
Batch Ingest from JSONLD

### ISSUE THREAD

**Issue by tpendragon** [OregonDigital/ControlledVocabularyManager#8]

**Comment by mickeroo** [comment]
Use case: to pull data in from other repositories e.g. opaque namespace

**Comment by terrellt** [comment]
After converting JSONLD to objects, we'll want an enrichment process to rip out bad metadata we know we have - stripping out issued_at/modified_at/defined_by.

**Comment by wickr** [comment]
See #105

**Comment by lsat12357** [comment]
this seems to be functional, but it overwrites previous versions. since the consensus seems to be that we're not going to use this beyond migrating vocabs that don't yet exist, we may be done with this. can it be closed?
